import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.YearMonth;
import java.time.format.TextStyle;
import java.util.Locale;

// PUBLIC CLASS: The main window of our application, extending JFrame to create a GUI.
public class CRUD_GUI_Backup extends JFrame {

    // STATIC FINAL: Constant formatters to keep Date and Time strings consistent throughout the app.
    static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("hh:mm a");
    static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    // VARIABLES: UI Components used for user input and data display.
    JTextField txtId;           // Holds the unique ID from the database (Primary Key).
    JTextField txtName;         // Input field for the Student's Name.
    JTextField txtDate;         // Displays the selected date for attendance.
    JTextField txtRemarks;      // Optional field for additional notes.
    JTextField txtSearch;       // Field used to search/filter records.
    JTextField txtFilterDate;   // Field used to filter records by a specific date.
    JComboBox<String> cmbAttendance; // Dropdown menu for selecting status (Present, Absent, etc.).
    JComboBox<String> cmbFilterAttendance; // Dropdown menu for filtering by status.
    JTable table;               // The visual table that shows data from MySQL.
    DefaultTableModel model;    // The "brain" of the table that manages the actual rows and columns.

    // VARIABLE: Keeps track of the date and subject currently selected by the user.
    LocalDate selectedDate = LocalDate.now();
    String selectedSubject = "General";

    // DATABASE CONSTANTS: Connection details for the MySQL server.
    static final String URL = "jdbc:mysql://localhost:3306/";
    static final String DB_NAME = "crud_gui_db";
    static final String USER = "root";
    static final String PASS = "Administrator.123";

    // LOGIN CREDENTIALS: Hardcoded admin access for the login screen.
    static final String LOGIN_USERNAME = "admin";
    static final String LOGIN_PASSWORD = "admin";

    // CONNECTION: The object that maintains the link between Java and MySQL.
    Connection con;

    // CONSTRUCTOR: This runs when the program starts. It sets up the window and components.
    public CRUD_GUI_Backup() {
        // WINDOW SETUP: Defining the title, size, and behavior of the main window.
        setTitle("Java-MySQL Based Attendance Monitoring System for College Students at MSEUF-Candelaria");
        setSize(1100, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centers the window on the screen.
        setLayout(new BorderLayout(30, 30));

        // MAIN PANEL: The container with padding to make the UI look clean.
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(30, 30, 30, 30));
        setContentPane(mainPanel);

        // TOP PANEL: Contains the Title, Input Form, and Buttons.
        JPanel topPanel = new JPanel(new BorderLayout(10, 10));

        // TITLE LABEL: Large header for the application.
        JLabel titleLabel = new JLabel("Student Attendance Monitoring System", JLabel.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 36));
        titleLabel.setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));
        topPanel.add(titleLabel, BorderLayout.NORTH);

        // FORM PANEL: A grid layout to organize labels and input fields side-by-side.
        JPanel formPanel = new JPanel(new GridLayout(5, 2, 10, 10));

        txtId = new JTextField();
        txtId.setEnabled(false); // ID is auto-generated by MySQL, so user cannot edit it.
        txtName = new JTextField();
        txtDate = new JTextField();
        txtDate.setEditable(false);
        txtDate.setText(selectedDate.format(DATE_FORMATTER) + " | " + selectedSubject);
        txtDate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        txtRemarks = new JTextField();
        cmbAttendance = new JComboBox<>(new String[]{"Present", "Absent", "Late", "Excuse"});

        formPanel.add(new JLabel("ID:"));
        formPanel.add(txtId);
        formPanel.add(new JLabel("Student Name:"));
        formPanel.add(txtName);
        formPanel.add(new JLabel("Date:"));
        formPanel.add(txtDate);
        formPanel.add(new JLabel("Attendance:"));
        formPanel.add(cmbAttendance);
        formPanel.add(new JLabel("Remarks:"));
        formPanel.add(txtRemarks);

        // BUTTON PANEL: Holds the Insert, Update, Delete, and Clear buttons.
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));

        JButton btnInsert = new JButton("Insert");
        JButton btnUpdate = new JButton("Update");
        JButton btnDelete = new JButton("Delete");
        JButton btnClear = new JButton("Clear");

        buttonPanel.add(btnInsert);
        buttonPanel.add(btnUpdate);
        buttonPanel.add(btnDelete);
        buttonPanel.add(btnClear);

        // FILTER PANEL: Responsive grid layout to keep filters visible on smaller windows.
        JPanel filterPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbcFilter = new GridBagConstraints();
        gbcFilter.insets = new Insets(5, 5, 5, 5);
        gbcFilter.fill = GridBagConstraints.HORIZONTAL;

        txtSearch = new JTextField(12);
        txtFilterDate = new JTextField(8);
        cmbFilterAttendance = new JComboBox<>(new String[]{"All", "Present", "Absent", "Late", "Excuse"});
        JButton btnSearch = new JButton("Search");
        JButton btnReset = new JButton("Reset Filter");

        // FIRST ROW: Search and Status
        gbcFilter.gridx = 0; gbcFilter.gridy = 0;
        filterPanel.add(new JLabel("Search:"), gbcFilter);
        gbcFilter.gridx = 1;
        filterPanel.add(txtSearch, gbcFilter);
        gbcFilter.gridx = 2;
        filterPanel.add(new JLabel("Status:"), gbcFilter);
        gbcFilter.gridx = 3;
        filterPanel.add(cmbFilterAttendance, gbcFilter);

        // SECOND ROW: Date and Buttons
        gbcFilter.gridx = 0; gbcFilter.gridy = 1;
        filterPanel.add(new JLabel("Date (YYYY-MM-DD):"), gbcFilter);
        gbcFilter.gridx = 1;
        filterPanel.add(txtFilterDate, gbcFilter);
        gbcFilter.gridx = 2;
        filterPanel.add(btnSearch, gbcFilter);
        gbcFilter.gridx = 3;
        filterPanel.add(btnReset, gbcFilter);

        // NORTH CONTENT: Groups the form, buttons, and filters. Uses BoxLayout for vertical stacking.
        JPanel northContent = new JPanel();
        northContent.setLayout(new BoxLayout(northContent, BoxLayout.Y_AXIS));
        northContent.add(formPanel);
        northContent.add(Box.createVerticalStrut(15));
        northContent.add(buttonPanel);
        northContent.add(Box.createVerticalStrut(15));
        northContent.add(filterPanel);

        topPanel.add(northContent, BorderLayout.CENTER);
        add(topPanel, BorderLayout.NORTH);

        // TABLE SETUP: Defines columns and prevents direct cell editing in the table.
        model = new DefaultTableModel(new String[]{"ID", "Student Name", "Subject", "Date", "Time", "Attendance", "Remarks"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table = new JTable(model);
        table.setRowHeight(35); // Large row height for better visibility.
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 18));
        add(new JScrollPane(table), BorderLayout.CENTER);

        // INITIALIZATION: Calls methods to connect to the DB and load the table.
        setupDatabase();
        loadData();

        // ACTION LISTENERS: Links button clicks to their respective Java methods.
        btnInsert.addActionListener(e -> insertData());
        btnUpdate.addActionListener(e -> updateData());
        btnDelete.addActionListener(e -> deleteData());
        btnClear.addActionListener(e -> clearFields());
        btnSearch.addActionListener(e -> loadData());
        cmbFilterAttendance.addActionListener(e -> loadData());
        btnReset.addActionListener(e -> {
            txtSearch.setText("");
            txtFilterDate.setText("");
            cmbFilterAttendance.setSelectedIndex(0);
            loadData();
        });

        // EVENT LISTENER: Opens a calendar popup when the date field is clicked.
        txtDate.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                LocalDate picked = CalendarPopup.pickDate(CRUD_GUI_Backup.this, selectedDate);
                if (picked != null) {
                    selectedDate = picked;

                    // SUBJECT POPUP: After picking a date, user picks a subject.
                    String[] subjects = {"Object Oriented Programming", "CpE as a Discipline" , "Calculus", "Physics", "AutoCAD", "Physical Education", "Panitikang Filipino", "University and I"};
                    String pickedSubject = (String) JOptionPane.showInputDialog(
                            CRUD_GUI_Backup.this,
                            "Select Subject:",
                            "Subject Selection",
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            subjects,
                            selectedSubject
                    );

                    if (pickedSubject != null) {
                        selectedSubject = pickedSubject;
                        txtDate.setText(selectedDate.format(DATE_FORMATTER) + " | " + selectedSubject);
                    }
                }
            }
        });

        // EVENT LISTENER: Fills the form fields when a user clicks a row in the table.
        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int i = table.getSelectedRow();
                if (i < 0) return;

                txtId.setText(model.getValueAt(i, 0).toString());
                txtName.setText(model.getValueAt(i, 1).toString());
                selectedSubject = model.getValueAt(i, 2).toString();

                Object dateValue = model.getValueAt(i, 3);
                if (dateValue instanceof java.util.Date) {
                    java.util.Date d = (java.util.Date) dateValue;
                    selectedDate = new java.sql.Date(d.getTime()).toLocalDate();
                    txtDate.setText(selectedDate.format(DATE_FORMATTER) + " | " + selectedSubject);
                } else if (dateValue != null) {
                    try {
                        java.sql.Date sqlDate = java.sql.Date.valueOf(dateValue.toString());
                        selectedDate = sqlDate.toLocalDate();
                        txtDate.setText(selectedDate.format(DATE_FORMATTER) + " | " + selectedSubject);
                    } catch (Exception ignore) {
                        selectedDate = LocalDate.now();
                        txtDate.setText(selectedDate.format(DATE_FORMATTER) + " | " + selectedSubject);
                    }
                }
                cmbAttendance.setSelectedItem(model.getValueAt(i, 5).toString());
                Object remarksValue = model.getValueAt(i, 6);
                txtRemarks.setText(remarksValue == null ? "" : remarksValue.toString());
            }
        });
    }

    // VOID METHOD: Handles database creation, table creation, and schema updates.
    void setupDatabase() {
        try {
            Connection tempCon = DriverManager.getConnection(URL, USER, PASS);
            Statement stmt = tempCon.createStatement();
            stmt.executeUpdate("CREATE DATABASE IF NOT EXISTS " + DB_NAME);
            tempCon.close();

            con = DriverManager.getConnection(URL + DB_NAME, USER, PASS);
            Statement dbStmt = con.createStatement();
            dbStmt.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS attendance_records (" +
                            "id INT AUTO_INCREMENT PRIMARY KEY," +
                            "student_name VARCHAR(100) NOT NULL," +
                            "subject_name VARCHAR(100) NOT NULL DEFAULT 'General'," +
                            "attendance_status VARCHAR(30) NOT NULL," +
                            "attendance_date DATE NOT NULL," +
                            "attendance_time VARCHAR(10) NOT NULL," +
                            "remarks TEXT NULL)"
            );

            // SCHEMA UPDATES: Checks if 'remarks', 'attendance_time', or 'subject_name' columns exist.
            PreparedStatement colCheck = con.prepareStatement(
                    "SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS " +
                            "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'attendance_records' AND COLUMN_NAME = 'remarks' LIMIT 1"
            );
            colCheck.setString(1, DB_NAME);
            ResultSet colRs = colCheck.executeQuery();
            if (!colRs.next()) {
                dbStmt.executeUpdate("ALTER TABLE attendance_records ADD COLUMN remarks TEXT NULL");
            }
            colRs.close();
            colCheck.close();

            PreparedStatement timeColCheck = con.prepareStatement(
                    "SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS " +
                            "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'attendance_records' AND COLUMN_NAME = 'attendance_time' LIMIT 1"
            );
            timeColCheck.setString(1, DB_NAME);
            ResultSet timeColRs = timeColCheck.executeQuery();
            if (!timeColRs.next()) {
                dbStmt.executeUpdate("ALTER TABLE attendance_records ADD COLUMN attendance_time VARCHAR(20) NOT NULL DEFAULT '---'");
            }
            timeColRs.close();
            timeColCheck.close();

            PreparedStatement subjectColCheck = con.prepareStatement(
                    "SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS " +
                            "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'attendance_records' AND COLUMN_NAME = 'subject_name' LIMIT 1"
            );
            subjectColCheck.setString(1, DB_NAME);
            ResultSet subjectColRs = subjectColCheck.executeQuery();
            if (!subjectColRs.next()) {
                dbStmt.executeUpdate("ALTER TABLE attendance_records ADD COLUMN subject_name VARCHAR(100) NOT NULL DEFAULT 'General'");
            }
            subjectColRs.close();
            subjectColCheck.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database setup failed: " + e.getMessage());
        }
    }

    // VOID METHOD: Reads data from MySQL and populates the JTable. Supports searching.
    void loadData() {
        String searchText = txtSearch == null ? "" : txtSearch.getText().trim();
        String filterDate = txtFilterDate == null ? "" : txtFilterDate.getText().trim();
        String filterStatus = (cmbFilterAttendance == null || cmbFilterAttendance.getSelectedIndex() == 0)
                ? "" : cmbFilterAttendance.getSelectedItem().toString();

        if (!filterDate.isEmpty() && !isValidDate(filterDate)) {
            JOptionPane.showMessageDialog(this, "Filter date must be in YYYY-MM-DD format.");
            return;
        }

        try {
            model.setRowCount(0); // Clear table before reloading.

            StringBuilder sql = new StringBuilder(
                    "SELECT id, student_name, subject_name, attendance_status, attendance_date, attendance_time, remarks " +
                            "FROM attendance_records WHERE 1=1"
            );

            if (!searchText.isEmpty()) {
                sql.append(" AND (student_name LIKE ? OR attendance_status LIKE ? OR remarks LIKE ? OR subject_name LIKE ?)");
            }
            if (!filterDate.isEmpty()) {
                sql.append(" AND attendance_date = ?");
            }
            if (!filterStatus.isEmpty()) {
                sql.append(" AND attendance_status = ?");
            }
            sql.append(" ORDER BY attendance_date DESC, id DESC");

            PreparedStatement pst = con.prepareStatement(sql.toString());
            int parameterIndex = 1;

            if (!searchText.isEmpty()) {
                String keyword = "%" + searchText + "%";
                pst.setString(parameterIndex++, keyword);
                pst.setString(parameterIndex++, keyword);
                pst.setString(parameterIndex++, keyword);
                pst.setString(parameterIndex++, keyword);
            }
            if (!filterDate.isEmpty()) {
                pst.setDate(parameterIndex++, Date.valueOf(filterDate));
            }
            if (!filterStatus.isEmpty()) {
                pst.setString(parameterIndex++, filterStatus);
            }

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("student_name"),
                        rs.getString("subject_name"),
                        rs.getDate("attendance_date"),
                        rs.getString("attendance_time"),
                        rs.getString("attendance_status"),
                        rs.getString("remarks")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable to load data: " + e.getMessage());
        }
    }

    // VOID METHOD: Inserts a new record into the database (CREATE in CRUD).
    void insertData() {
        if (!validateForm(false)) return;

        try {
            // DUPLICATE CHECK: Prevent marking the same student for the same subject on the same day.
            PreparedStatement checkPst = con.prepareStatement(
                    "SELECT 1 FROM attendance_records WHERE student_name = ? AND attendance_date = ? AND subject_name = ?"
            );
            checkPst.setString(1, txtName.getText().trim());
            checkPst.setDate(2, java.sql.Date.valueOf(selectedDate));
            checkPst.setString(3, selectedSubject);
            ResultSet rs = checkPst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Attendance for " + txtName.getText().trim() + " in " + selectedSubject + " has already been recorded for this date.");
                return;
            }

            PreparedStatement pst = con.prepareStatement(
                    "INSERT INTO attendance_records(student_name, subject_name, attendance_status, attendance_date, attendance_time, remarks) VALUES (?, ?, ?, ?, ?, ?)"
            );
            String status = cmbAttendance.getSelectedItem().toString();
            pst.setString(1, txtName.getText().trim());
            pst.setString(2, selectedSubject);
            pst.setString(3, status);
            pst.setDate(4, java.sql.Date.valueOf(selectedDate));

            String time = (status.equalsIgnoreCase("Absent") || status.equalsIgnoreCase("Excuse")) ? "---" : LocalTime.now().format(TIME_FORMATTER);
            pst.setString(5, time);
            pst.setString(6, txtRemarks.getText().trim());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Inserted!");
            loadData();
            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Insert failed: " + e.getMessage());
        }
    }

    // VOID METHOD: Updates an existing record based on the ID (UPDATE in CRUD).
    void updateData() {
        if (!validateForm(true)) return;

        try {
            PreparedStatement pst = con.prepareStatement(
                    "UPDATE attendance_records SET student_name=?, subject_name=?, attendance_status=?, attendance_date=?, attendance_time=?, remarks=? WHERE id=?"
            );
            String status = cmbAttendance.getSelectedItem().toString();
            pst.setString(1, txtName.getText().trim());
            pst.setString(2, selectedSubject);
            pst.setString(3, status);
            pst.setDate(4, java.sql.Date.valueOf(selectedDate));

            String time = (status.equalsIgnoreCase("Absent") || status.equalsIgnoreCase("Excuse")) ? "---" : LocalTime.now().format(TIME_FORMATTER);
            pst.setString(5, time);
            pst.setString(6, txtRemarks.getText().trim());
            pst.setInt(7, Integer.parseInt(txtId.getText().trim()));

            int updated = pst.executeUpdate();
            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Updated!");
                loadData();
                clearFields();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Update failed: " + e.getMessage());
        }
    }

    // VOID METHOD: Removes a record from the database using its ID (DELETE in CRUD).
    void deleteData() {
        if (txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a record first before deleting.");
            return;
        }

        try {
            PreparedStatement pst = con.prepareStatement("DELETE FROM attendance_records WHERE id=?");
            pst.setInt(1, Integer.parseInt(txtId.getText().trim()));

            int deleted = pst.executeUpdate();
            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Deleted!");
                loadData();
                clearFields();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Delete failed: " + e.getMessage());
        }
    }

    // BOOLEAN METHOD: Returns true if the form is valid, false if fields are missing.
    boolean validateForm(boolean requireId) {
        if (requireId && txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a record first.");
            return false;
        }
        if (txtName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student name is required.");
            return false;
        }
        return true;
    }

    // BOOLEAN METHOD: Validates if a string follows the correct YYYY-MM-DD format.
    boolean isValidDate(String value) {
        try {
            Date.valueOf(value);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    // VOID METHOD: Resets all UI components to their default empty state.
    void clearFields() {
        txtId.setText("");
        txtName.setText("");
        selectedDate = LocalDate.now();
        selectedSubject = "General";
        txtDate.setText(selectedDate.format(DATE_FORMATTER) + " | " + selectedSubject);
        txtRemarks.setText("");
        cmbAttendance.setSelectedIndex(0);
        table.clearSelection();
    }

    // STATIC INNER CLASS: A custom calendar dialog for selecting dates.
    static class CalendarPopup {
        static LocalDate pickDate(Component parent, LocalDate initial) {
            JDialog dialog = new JDialog(SwingUtilities.getWindowAncestor(parent), "Select Date", Dialog.ModalityType.APPLICATION_MODAL);
            dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

            LocalDate[] result = {null};
            YearMonth[] shownMonth = {YearMonth.from(initial == null ? LocalDate.now() : initial)};

            JPanel root = new JPanel(new BorderLayout(10, 10));
            root.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

            JLabel monthLabel = new JLabel("", SwingConstants.CENTER);
            monthLabel.setFont(new Font("Arial", Font.BOLD, 22));

            JButton prev = new JButton("<");
            JButton next = new JButton(">");
            JPanel header = new JPanel(new BorderLayout(10, 0));
            header.add(prev, BorderLayout.WEST);
            header.add(monthLabel, BorderLayout.CENTER);
            header.add(next, BorderLayout.EAST);
            root.add(header, BorderLayout.NORTH);

            JPanel grid = new JPanel(new GridLayout(0, 7, 6, 6));
            root.add(grid, BorderLayout.CENTER);

            JButton cancel = new JButton("Cancel");
            JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            footer.add(cancel);
            root.add(footer, BorderLayout.SOUTH);

            // RUNNABLE: Logic to redraw the calendar when the user changes months.
            Runnable rebuild = () -> {
                grid.removeAll();
                YearMonth ym = shownMonth[0];
                monthLabel.setText(ym.getMonth().getDisplayName(TextStyle.FULL, Locale.getDefault()) + " " + ym.getYear());

                DayOfWeek[] week = {DayOfWeek.SUNDAY, DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY, DayOfWeek.FRIDAY, DayOfWeek.SATURDAY};
                for (DayOfWeek dow : week) {
                    JLabel lbl = new JLabel(dow.getDisplayName(TextStyle.SHORT, Locale.getDefault()), SwingConstants.CENTER);
                    lbl.setFont(lbl.getFont().deriveFont(Font.BOLD));
                    grid.add(lbl);
                }

                int firstDayIndex = ym.atDay(1).getDayOfWeek().getValue() % 7;
                for (int i = 0; i < firstDayIndex; i++) grid.add(new JLabel(""));

                int length = ym.lengthOfMonth();
                for (int day = 1; day <= length; day++) {
                    LocalDate d = ym.atDay(day);
                    JButton b = new JButton(String.valueOf(day));
                    if (d.equals(LocalDate.now())) b.setFont(b.getFont().deriveFont(Font.BOLD));
                    b.addActionListener(e -> {
                        result[0] = d;
                        dialog.dispose();
                    });
                    grid.add(b);
                }
                dialog.pack();
                dialog.setLocationRelativeTo(parent);
                grid.revalidate();
                grid.repaint();
            };

            prev.addActionListener(e -> { shownMonth[0] = shownMonth[0].minusMonths(1); rebuild.run(); });
            next.addActionListener(e -> { shownMonth[0] = shownMonth[0].plusMonths(1); rebuild.run(); });
            cancel.addActionListener(e -> { result[0] = null; dialog.dispose(); });

            dialog.setContentPane(root);
            dialog.setResizable(false);
            rebuild.run();
            dialog.setVisible(true);

            return result[0];
        }
    }

    // PRIVATE STATIC METHOD: Displays a login window before the main app opens.
    private static boolean showLoginDialog() {
        final JDialog dialog = new JDialog((Frame) null, "Login", true);
        dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        JPanel content = new JPanel(new BorderLayout(12, 12));
        content.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        JLabel title = new JLabel("Please login to continue", SwingConstants.CENTER);
        title.setFont(new Font("Arial", Font.BOLD, 24));
        content.add(title, BorderLayout.NORTH);

        JPanel form = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(6, 6, 6, 6);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JTextField txtUsername = new JTextField(18);
        JPasswordField txtPassword = new JPasswordField(18);

        gbc.gridx = 0; gbc.gridy = 0;
        form.add(new JLabel("Username:"), gbc);
        gbc.gridx = 1;
        form.add(txtUsername, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        form.add(new JLabel("Password:"), gbc);
        gbc.gridx = 1;
        form.add(txtPassword, gbc);

        content.add(form, BorderLayout.CENTER);

        JPanel buttons = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0));
        JButton btnLogin = new JButton("Login");
        JButton btnCancel = new JButton("Cancel");
        buttons.add(btnLogin);
        buttons.add(btnCancel);
        content.add(buttons, BorderLayout.SOUTH);

        final boolean[] authenticated = {false};

        btnLogin.addActionListener(e -> {
            if (LOGIN_USERNAME.equals(txtUsername.getText().trim()) && LOGIN_PASSWORD.equals(new String(txtPassword.getPassword()))) {
                authenticated[0] = true;
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog, "Invalid credentials.");
            }
        });
        btnCancel.addActionListener(e -> dialog.dispose());

        dialog.setContentPane(content);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

        return authenticated[0];
    }

    // PRIVATE STATIC METHOD: Applies a uniform font to all UI components for accessibility.
    private static void setUIFont(javax.swing.plaf.FontUIResource f) {
        java.util.Enumeration<Object> keys = UIManager.getDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof javax.swing.plaf.FontUIResource) {
                UIManager.put(key, f);
            }
        }
    }

    // PUBLIC STATIC VOID MAIN: The entry point of the program.
    public static void main(String[] args) {
        setUIFont(new javax.swing.plaf.FontUIResource(new Font("Arial", Font.PLAIN, 18)));
        SwingUtilities.invokeLater(() -> {
            if (showLoginDialog()) {
                new CRUD_GUI().setVisible(true);
            } else {
                System.exit(0);
            }
        });
    }
}
